config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root to: "questions#home"
  get "ask", to: "questions#ask"
  get "answer", to: "questions#answer"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def ask

  end

  def answer
    @question = params[:question]

    if @question == "I am going to work"
      @coach_response = "Great!"
    elsif @question&.end_with?("?")
      @coach_response = "Silly question, get dressed and go to work!"
    else
      @coach_response = "I don't care, get dressed and go to work!"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/answer.html.erb
<h1>List of Questions and Answers</h1>

<p>Your message: <strong><%= @question %></strong></p>
<p>Coach says: <strong><%= @coach_response %></strong></p>

<ul>
  <li><%= link_to "Ask another question", ask_path %></li>
  <li><%= link_to "home page", root_path %></li>
</ul>

app/views/questions/ask.html.erb
<h1>Question to Coach</h1>

<form action="/answer" method="get" data-turbo="false">
  <input type="text" name="question" placeholder="Type a question" required>
  <input type="submit" value="Ask!">
</form>

<%= link_to "home page", root_path %>

app/views/questions/home.html.erb
<h1>Question's Dashboard</h1>

<ul>
  <li><%= link_to "Make a question", ask_path %></li>
  <li><%= link_to "List of questions and answers", answer_path %></li>
</ul>